### PR TITLE
read and load functionality for JLD files containing groups

### PR DESCRIPTION
**Pull request by DSLituiev**
I added the functionality discussed in [issue #257](https://github.com/timholy/HDF5.jl/issues/257#issuecomment-136009599)

### CODE REVIEW

**Comment by DSLituiev** [comment]
Test cases:

```
jldfile = "testgroup.jld"
jldopen(jldfile , "w") do file
    g = g_create(file, "autocorr") # create a group
    g["countsmapdistfreq"] = "abracadabra"
    g = g_create(file, "autocorr") # create a group
    g["countsmapdistfreq"] = "abracadabra"
    g["xvect"] = 1:20
    file["stray"] = "cat"
end
```
Load:
```
load(jldfile)
Dict{Union(ASCIIString,UTF8String),Any} with 2 entries:
  "autocorr" => ["xvect"=>1:20,"countsmapdistfreq"=>"abracadabra"]
  "stray"    => "cat"
```
```

**Comment by timholy** [comment]
If you could add those test cases to one of the test files, this looks good to merge.

**Comment by DSLituiev** [comment]
Shall I add my test file or append to any existing one? If latter, which one?

**Comment by timholy** [comment]
Could probably be the main runtests.jl file. I don't have strong feelings, however.

**Comment by timholy** [comment]
Sorry, I didn't explain very well. Instead of adding something to one of the .jld files, could you copy/paste the julia code that's up above into one of the .jl files? Then your test would look like this:
```jl
# Create jldfile ("testgroup.jld") as above

# Now we check whether it worked properly
vars = load(jldfile)
@test var["autocorr"]["xvect"] == 1:20
@test vars["autocorr"]["countsmapdistfreq"] == "abracadabra"
@test vars["stray"] == "cat"
```

**Comment by DSLituiev** [comment]
Sorry, my bad, added a wrong file. Please check

**Comment by timholy** [comment]
You're fine, thanks for the rapid fix (and sorry it took me so long to come back here and check).

I hate to keep pestering you, but now there's a whole bunch of "extraneous" commits (over 250). Would you like me to check out your branch for you and fix the problems (you'll still get credited as the author), or do you want to venture into the slightly-scary world of [`git rebase`](http://docs.julialang.org/en/latest/manual/packages/#squashing-and-rebasing)? Just let me know. I really appreciate your patience.

**Comment by DSLituiev** [comment]
I am afraid it will take me a four hours on my own. I would really appreciate if you clean it for me.

**Comment by timholy** [comment]
@DSLituiev, see https://github.com/JuliaLang/JLD.jl/commits/master. I meant to push this as a branch, but I guess because yours was on master, my branch pushed to master.

Thanks for the contribution!

**Pull request closed without merging**
