### PR TITLE
Add Appveyor fast-fail feature

### PR DESCRIPTION
**Pull request by tkelman**

### CODE REVIEW

**Comment by timholy** [comment]
Meanwhile, https://github.com/JuliaLang/Compat.jl/commit/5f534b055d6fcda4761078e47a00d60b14bc817f should deal with another problem (once I tag a new version).

**Comment by tkelman** [comment]
Yeah, noticed something in the Travis release failures here. I wonder whether your appveyor account is on the fast VM's or the slow ones. The Julia installer really shouldn't take more than 30-60 seconds to run.

**Comment by tkelman** [comment]
Alrighty. Looks like the caching might just work with the mechanisms we already have in place. I'm going to go deal with that at WinRPM, so don't merge this in its current form.

**Comment by timholy** [comment]
@tkelman, I'll leave it up to you to decide when to merge.

**Pull request merged**
