### PR TITLE
Union() -> Union{}

### PR DESCRIPTION
**Pull request by yuyichao**
Let's see if I understand how it works correctly....

### CODE REVIEW

**Comment by yuyichao** [comment]
The rest of the depwarns should be fixed by https://github.com/timholy/JLDArchives.jl/pull/6

**Comment by yuyichao** [comment]
Hmm. The failure seems to be not 100% repeatable.....

**Comment by yuyichao** [comment]
I reverted the change of `full_typename` of `Union` types and the intermittent error goes away locally. I guess I still don't fully understand how this works or there's still some implecit assumption about how Union is serialized...

**Comment by timholy** [comment]
I haven't looked at the error(s) in any detail, but to possibly catch you up on an important fact: the typename gets encoded in the file as a string. If you're reading an older file written before it became `Union{x,y,z}`, it may be written as the string `"Union(x,y,z)"`.

Not sure if that's news to you or helps in any way, but there you have it.

**Comment by yuyichao** [comment]
IIUC, it should be translated back in fixtype but somehow not reliably in this case?

**Comment by yuyichao** [comment]
The current one should be conservative. The change of how Union type is stored can probably be changed later....

**Pull request merged**
