### PR TITLE
Fix recent deprecations, including `require`

### PR DESCRIPTION
**Pull request by timholy**
The `require` part of this is the part that needs careful thought. See comments in that commit.

### CODE REVIEW

**Comment by timholy** [comment]
@tkelman, any ideas why there are 8 jobs cued on AppVeyor? It looks like it's just two commits that are being tested.

**Comment by tkelman** [comment]
It's because your `appveyor.yml` doesn't have a `branches: only:` section. See https://github.com/JuliaOpt/CoinOptServices.jl/blob/master/appveyor.yml for the full-featured version, including the "cancel if newer PR builds pending" snippet that I didn't include in Example.jl.

**Comment by timholy** [comment]
Thanks, @tkelman. However, the "newer builds" part of this didn't seem to work. I wonder if I have some kind of settings problem?

Next we'll have to figure out why the (earlier) AppVeyor tests seem to be frozen. Unless you have some good ideas, I might submit a test PR that just contains the appveyor.yml change (once we get it into proper shape).

**Comment by tkelman** [comment]
Oh. Hm. Well my powershell scripting might be buggy, or not be reflecting something from the API correctly. We should probably split that out into a separate branch (you can temporarily add branches to the whitelist in the branches' copy of `appveyor.yml` if you want to test something without opening a PR for it, but maybe easier for the sake of debugging conversation to open a separate one anyway) and look at the different environment variable values, try the same API query ourselves, etc.

**Comment by tkelman** [comment]
Hm, this is still getting twice as many builds triggered as it's supposed to. Could you go to the github settings for this repo under webhooks and see if there's maybe a duplicate entry for appveyor?

**Comment by timholy** [comment]
Yep, that was it. Thanks!

**Comment by timholy** [comment]
I'm going to close this out and prepare a new version that just handles `addrequire`. But not today.

**Pull request closed without merging**
